### ISSUE TITLE
Option to not record in FIT

### ISSUE THREAD

**Issue by TrippyZ** [imgrant/FlexiRunner#3]
Any chance of an option to not record in the FIT?  I have been having a bit of breakage with a few different CIQ fields impacting on syncing/uploading to various GC alternatives.

**Comment by imgrant** [comment]
I'm unlikely to add this to Flexirunner – the problem lies with whichever site you are trying to upload to, and them not properly supporting the FIT 2.0 format (or, you could blame Garmin for not making the FIT format properly backwards compatible...). To make this an option in Flexirunner is a workaround (which would incur memory overhead), the correct way to resolve this is for the site(s) to update their FIT support, please contact them directly. Alternatively, you can take the Flexirunner code and build your own version that strips out the FIT field writing bits.
